group=crud
template.count=10
template.0.source=domain-model.java.ftl
template.0.output=${crud.basePackagePath}/domain/${crud.resourcePackage}/${crud.resourceName}.java
template.1.source=domain-repository.java.ftl
template.1.output=${crud.basePackagePath}/domain/${crud.resourcePackage}/${crud.resourceName}Repository.java
template.2.source=application-service.java.ftl
template.2.output=${crud.basePackagePath}/application/${crud.resourcePackage}/${crud.resourceName}ApplicationService.java
template.3.source=mybatis-entity.java.ftl
template.3.output=${crud.basePackagePath}/infrastructure/${crud.resourcePackage}/${crud.resourceName}Entity.java
template.4.source=mybatis-mapper.java.ftl
template.4.output=${crud.basePackagePath}/infrastructure/${crud.resourcePackage}/${crud.resourceName}Mapper.java
template.5.source=mybatis-repository.java.ftl
template.5.output=${crud.basePackagePath}/infrastructure/${crud.resourcePackage}/MybatisPlus${crud.resourceName}Repository.java
template.6.source=rest-controller.java.ftl
template.6.output=${crud.basePackagePath}/interfaces/rest/${crud.resourcePackage}/${crud.resourceName}Controller.java
template.7.source=create-request.java.ftl
template.7.output=${crud.basePackagePath}/interfaces/rest/${crud.resourcePackage}/dto/Create${crud.resourceName}Request.java
template.8.source=update-request.java.ftl
template.8.output=${crud.basePackagePath}/interfaces/rest/${crud.resourcePackage}/dto/Update${crud.resourceName}Request.java
template.9.source=response.java.ftl
template.9.output=${crud.basePackagePath}/interfaces/rest/${crud.resourcePackage}/dto/${crud.resourceName}Response.java
